/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#283044",
        "on-secondary-fixed": "#001f26",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#452000",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#703700",
        "on-surface": "#dae2fd",
        "error-container": "#93000a",
        "primary-fixed-dim": "#c0c1ff",
        "primary-container": "#8083ff",
        "inverse-primary": "#494bd6",
        "surface-container-low": "#131b2e",
        "on-error": "#690005",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-lowest": "#060e20",
        "surface-variant": "#2d3449",
        "surface-container-highest": "#2d3449",
        "surface-dim": "#0b1326",
        "on-secondary-container": "#00424e",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#acedff",
        "on-tertiary": "#4f2500",
        "background": "#0b1326",
        "on-primary-container": "#0d0096",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb783",
        "on-secondary": "#003640",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        "surface": "#0b1326",
        "primary": "#c0c1ff",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed-variant": "#004e5c",
        "outline": "#908fa0",
        "tertiary": "#ffb783",
        "error": "#ffb4ab",
        "surface-container-high": "#222a3d",
        "on-primary": "#1000a9",
        "tertiary-container": "#d97721",
        "on-primary-fixed": "#07006c",
        "primary-fixed": "#e1e0ff",
        "on-background": "#dae2fd",
        "secondary": "#4cd7f6",
        "surface-container": "#171f33",
        "secondary-container": "#03b5d3",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "component-padding-y": "8px",
        unit: "4px",
        "component-padding-x": "12px",
        "container-margin": "24px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        "headline-lg": ["Inter"],
        "code-sm": ["Space Grotesk"],
        "display-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
